baseURL = "https://skelli.win/"
title = "Skelli"
theme = "glim"
defaultContentLanguage = "en"
disableKinds = ["taxonomy", "term"]

[languages.en]
locale = "en-us"
label = "English"
weight = 1

[taxonomies]
  technology = "technologies"
  vulnerability = "vulnerabilities"

[params]
  title = "Skelli"
  description = "Cyberpunk nonsense and writeups"
  
  # Add phrases for the typewriter effect
  phrases = [
    "Hacker",
    "Skeleton with Sudo Access",
    "Chaos Itself",
    "Anxiety as a Service",
    "Therapy via Terminal",
    "Shell Gremlin",
  ]
  
  # Add your navigation links/buttons
  links = [
    { name = "About", url = "/about", newTab = false },
    { name = "Blog", url = "/posts", newTab = false },
    { name = "Projects", url = "/projects", newTab = false },
    { name = "DIVD", url = "https://www.divd.nl/who-we-are/team/people/eden-stroet/", newTab = true },
    { name = "HackerOne", url = "https://hackerone.com/mrsskelli", newTab = true },
    { name = "Bugcrowd", url = "https://bugcrowd.com/h/mrs-skelli", newTab = true },
    { name = "Intigriti", url = "https://app.intigriti.com/researcher/profile/mrs_sk3ll1", newTab = true },
    { name = "Patchstack", url = "https://vdp.patchstack.com/database/researchers/e07dca4f-a20e-4804-979a-193415b9720a", newTab = true },
    { name = "Digital Overdose", url = "https://digitaloverdose.tech/", newTab = true },
    { name = "Github", url = "https://github.com/Mrs-Skelli", newTab = true },
    { name = "BlueSky", url = "https://bsky.app/profile/skelli@skelli.win", newTab = true },
    { name = "Mastodon", url = "https://infosec.exchange/@Mrs_Skelli", newTab = true },
    { name = "LinkedIn", url = "https://www.linkedin.com/in/mrsskelli/", newTab = true },
  ]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = false
